export default
    [{
        flightTime: "07:29",
        from: "CHN",
        date: "03 Feb",
        timeLeft: "5hrs 20 mins",
        endTime: "19:27",
        to: "JAI",
        endDate: "19 Feb",
        price: 7000,
        onlyHandbags: true,
    },
    {
        flightTime: "12:05",
        from: "MUM",
        date: "21 Jan",
        timeLeft: "3hrs 16 mins",
        endTime: "14:00",
        to: "MAT",
        endDate: "21 Jan",
        price: 12000,
        onlyHandbags: false,
    },
    {
        flightTime: "17:25",
        from: "TIR",
        date: "17 Mar",
        timeLeft: "7hrs 26 mins",
        endTime: "19:00",
        to: "LON",
        endDate: "23 Mar",
        price: 27500,
        onlyHandbags: false,
    },
    {
        flightTime: "07:15",
        from: "PUN",
        date: "14 Dec",
        timeLeft: "15hrs",
        endTime: "19:30",
        to: "TOK",
        endDate: "17 Dec",
        price: 7500,
        onlyHandbags: true,
    },
    {
        flightTime: "12:00",
        from: "MUM",
        date: "28 Sep",
        timeLeft: "37hrs 26 mins",
        endTime: "23:30",
        to: "MON",
        endDate: "31 Sep",
        price: 76500,
        onlyHandbags: true,
    },
    {
        flightTime: "11:25",
        from: "LUC",
        date: "13 May",
        timeLeft: "2hrs 26 mins",
        endTime: "13:00",
        to: "MUM",
        endDate: "13 May",
        price: 3500,
        onlyHandbags: false,
    }, {
        flightTime: "17:25",
        from: "KOL",
        date: "15 Aug",
        timeLeft: "37hrs 26 mins",
        endTime: "11:45",
        to: "CAL",
        endDate: "19 Aug",
        price: 45500,
        onlyHandbags: false,
    },];